import AppKit
import PDFKit

// PDFExporter lays out a deck's cards as a printable PDF document.
//
// Layout:
//   • A4 page (595 × 842 pt)
//   • 36 pt page margins
//   • 2 card columns, 3 rows per page = 6 cards per page
//   • Each card box is 243 × 118 pt with 10 pt gutter between columns/rows
//   • A header line showing the deck name is drawn at the top of every page
//   • Each card box shows:
//       – front text  (Georgia Bold 14 pt) in the top half
//       – a 1 pt hairline divider
//       – back text   (Georgia      12 pt) in the bottom half
//
// The exporter works by:
//   1. Creating a CGContext backed by an NSMutableData using CGContext(consumer:mediaBox:_:).
//   2. Drawing each page by hand with CoreGraphics primitives.
//   3. Wrapping the result in a PDFDocument loaded from the resulting Data.

enum PDFExporter {

    // MARK: - Public API

    /// Builds and returns a PDFDocument containing all of `deck`'s cards.
    static func export(deck: Deck) -> PDFDocument {
        let data = NSMutableData()
        let mediaBox = CGRect(origin: .zero, size: PageLayout.pageSize)

        var boxRef = mediaBox
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
              let context  = CGContext(consumer: consumer, mediaBox: &boxRef, nil)
        else {
            return PDFDocument()
        }

        let cards = deck.cards.sorted { $0.createdAt < $1.createdAt }
        let chunks = cards.chunked(into: PageLayout.cardsPerPage)

        for (pageIndex, pageCards) in chunks.enumerated() {
            beginPage(in: context, mediaBox: mediaBox)
            drawPageHeader(deck: deck, pageNumber: pageIndex + 1,
                           totalPages: chunks.count, in: context)
            for (slotIndex, card) in pageCards.enumerated() {
                let frame = cardFrame(slot: slotIndex)
                drawCard(card, in: frame, context: context)
            }
            endPage(in: context)
        }

        // Emit an empty page if the deck has no cards, so callers always get a valid doc
        if cards.isEmpty {
            beginPage(in: context, mediaBox: mediaBox)
            drawPageHeader(deck: deck, pageNumber: 1, totalPages: 1, in: context)
            endPage(in: context)
        }

        context.flush()

        guard let pdfDoc = PDFDocument(data: data as Data) else {
            return PDFDocument()
        }
        return pdfDoc
    }

    /// Writes the PDF generated by `export(deck:)` to `url`.
    static func save(deck: Deck, to url: URL) throws {
        let doc = export(deck: deck)
        guard let data = doc.dataRepresentation() else {
            throw PDFExportError.renderFailed
        }
        try data.write(to: url, options: .atomic)
    }

    // MARK: - Layout constants

    private enum PageLayout {
        static let pageSize     = CGSize(width: 595, height: 842)   // A4
        static let pageMargin:  CGFloat = 36
        static let headerHeight:CGFloat = 28
        static let gutter:      CGFloat = 10
        static let columns      = 2
        static let rows         = 3
        static var cardsPerPage: Int { columns * rows }

        // Derived card dimensions
        static var cardWidth: CGFloat {
            let usable = pageSize.width - 2 * pageMargin - CGFloat(columns - 1) * gutter
            return usable / CGFloat(columns)
        }
        static var cardHeight: CGFloat {
            let usable = pageSize.height - 2 * pageMargin - headerHeight - 8
                       - CGFloat(rows - 1) * gutter
            return usable / CGFloat(rows)
        }
    }

    // MARK: - Frame calculation

    /// Returns the CGRect for card slot `index` (0-based, left-to-right, top-to-bottom).
    private static func cardFrame(slot: Int) -> CGRect {
        let col = slot % PageLayout.columns
        let row = slot / PageLayout.columns

        // PDF coordinate origin is bottom-left; row 0 is the TOP row.
        let contentTop = PageLayout.pageSize.height
                       - PageLayout.pageMargin
                       - PageLayout.headerHeight - 8

        let x = PageLayout.pageMargin + CGFloat(col) * (PageLayout.cardWidth + PageLayout.gutter)
        let y = contentTop
              - CGFloat(row + 1) * PageLayout.cardHeight
              - CGFloat(row)     * PageLayout.gutter

        return CGRect(x: x, y: y,
                      width: PageLayout.cardWidth, height: PageLayout.cardHeight)
    }

    // MARK: - Page lifecycle

    private static func beginPage(in ctx: CGContext, mediaBox: CGRect) {
        var box = mediaBox
        ctx.beginPage(mediaBox: &box)
    }

    private static func endPage(in ctx: CGContext) {
        ctx.endPage()
    }

    // MARK: - Header

    private static func drawPageHeader(deck: Deck, pageNumber: Int,
                                       totalPages: Int, in ctx: CGContext) {
        let headerY = PageLayout.pageSize.height - PageLayout.pageMargin - PageLayout.headerHeight + 4

        // Deck name (left-aligned)
        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont(name: "Georgia-Bold", size: 13) ?? NSFont.boldSystemFont(ofSize: 13),
            .foregroundColor: NSColor.black,
        ]
        let titleStr = NSAttributedString(string: deck.name, attributes: titleAttrs)
        let titleRect = CGRect(x: PageLayout.pageMargin, y: headerY,
                               width: PageLayout.pageSize.width / 2 - PageLayout.pageMargin,
                               height: PageLayout.headerHeight)
        drawAttributedString(titleStr, in: titleRect, context: ctx)

        // Page number (right-aligned)
        let pageAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont(name: "Georgia", size: 11) ?? NSFont.systemFont(ofSize: 11),
            .foregroundColor: NSColor.darkGray,
        ]
        let pageStr = NSAttributedString(string: "Page \(pageNumber) of \(totalPages)",
                                         attributes: pageAttrs)
        let pageRect = CGRect(x: PageLayout.pageSize.width / 2,
                              y: headerY,
                              width: PageLayout.pageSize.width / 2 - PageLayout.pageMargin,
                              height: PageLayout.headerHeight)
        let paraStyle = NSMutableParagraphStyle()
        paraStyle.alignment = .right
        let pageStrAligned = NSMutableAttributedString(attributedString: pageStr)
        pageStrAligned.addAttribute(.paragraphStyle, value: paraStyle,
                                     range: NSRange(location: 0, length: pageStrAligned.length))
        drawAttributedString(pageStrAligned, in: pageRect, context: ctx)

        // Separator line below header
        let lineY = headerY - 4
        ctx.saveGState()
        ctx.setStrokeColor(NSColor.lightGray.cgColor)
        ctx.setLineWidth(0.5)
        ctx.move(to: CGPoint(x: PageLayout.pageMargin, y: lineY))
        ctx.addLine(to: CGPoint(x: PageLayout.pageSize.width - PageLayout.pageMargin, y: lineY))
        ctx.strokePath()
        ctx.restoreGState()
    }

    // MARK: - Card drawing

    private static func drawCard(_ card: OboerCard, in frame: CGRect, context ctx: CGContext) {
        let cornerRadius: CGFloat = 6
        let borderColor          = NSColor(white: 0.75, alpha: 1)
        let padding: CGFloat     = 8

        // Card border / background
        ctx.saveGState()
        let path = CGPath(roundedRect: frame, cornerWidth: cornerRadius,
                          cornerHeight: cornerRadius, transform: nil)
        ctx.setFillColor(NSColor.white.cgColor)
        ctx.addPath(path)
        ctx.fillPath()
        ctx.setStrokeColor(borderColor.cgColor)
        ctx.setLineWidth(0.75)
        ctx.addPath(path)
        ctx.strokePath()
        ctx.restoreGState()

        // Split the card vertically: top half = front, bottom half = back
        let halfH       = frame.height / 2
        let frontRect   = CGRect(x: frame.minX + padding,
                                 y: frame.midY,
                                 width: frame.width - 2 * padding,
                                 height: halfH - padding)
        let backRect    = CGRect(x: frame.minX + padding,
                                 y: frame.minY + padding,
                                 width: frame.width - 2 * padding,
                                 height: halfH - padding)

        // Divider
        ctx.saveGState()
        ctx.setStrokeColor(NSColor(white: 0.82, alpha: 1).cgColor)
        ctx.setLineWidth(0.5)
        ctx.move(to: CGPoint(x: frame.minX + padding, y: frame.midY))
        ctx.addLine(to: CGPoint(x: frame.maxX - padding, y: frame.midY))
        ctx.strokePath()
        ctx.restoreGState()

        // Front text
        let frontFont = NSFont(name: "Georgia-Bold", size: 13) ?? NSFont.boldSystemFont(ofSize: 13)
        let frontAttrs: [NSAttributedString.Key: Any] = [
            .font: frontFont,
            .foregroundColor: NSColor.black,
        ]
        let frontParaStyle = NSMutableParagraphStyle()
        frontParaStyle.alignment = .center
        frontParaStyle.lineBreakMode = .byWordWrapping
        var frontAttrsFull = frontAttrs
        frontAttrsFull[.paragraphStyle] = frontParaStyle

        let frontText = card.cardType == .cloze
            ? (card.clozeText ?? card.frontText)
            : card.frontText
        let frontStr = NSAttributedString(string: frontText.truncated(120), attributes: frontAttrsFull)
        drawAttributedString(frontStr, in: frontRect, context: ctx, verticalAlign: .center)

        // Back text
        let backFont = NSFont(name: "Georgia", size: 11) ?? NSFont.systemFont(ofSize: 11)
        let backParaStyle = NSMutableParagraphStyle()
        backParaStyle.alignment = .center
        backParaStyle.lineBreakMode = .byWordWrapping
        let backAttrs: [NSAttributedString.Key: Any] = [
            .font: backFont,
            .foregroundColor: NSColor.darkGray,
            .paragraphStyle: backParaStyle,
        ]
        let backText = card.backText.isEmpty ? "—" : card.backText
        let backStr  = NSAttributedString(string: backText.truncated(120), attributes: backAttrs)
        drawAttributedString(backStr, in: backRect, context: ctx, verticalAlign: .center)
    }

    // MARK: - Attributed string drawing helpers

    private enum VerticalAlignment { case top, center }

    /// Draws `string` inside `rect` using NSGraphicsContext wrapping `ctx`.
    private static func drawAttributedString(_ string: NSAttributedString,
                                             in rect: CGRect,
                                             context ctx: CGContext,
                                             verticalAlign: VerticalAlignment = .top) {
        // Measure text height so we can center it vertically
        let framesetter = CTFramesetterCreateWithAttributedString(string)
        let fitSize = CTFramesetterSuggestFrameSizeWithConstraints(
            framesetter,
            CFRangeMake(0, 0),
            nil,
            CGSize(width: rect.width, height: CGFloat.greatestFiniteMagnitude),
            nil
        )

        let drawRect: CGRect
        switch verticalAlign {
        case .top:
            drawRect = rect
        case .center:
            let offsetY = max(0, (rect.height - fitSize.height) / 2)
            drawRect = CGRect(x: rect.minX, y: rect.minY + offsetY,
                              width: rect.width, height: fitSize.height)
        }

        // Use NSGraphicsContext to leverage NSAttributedString's drawing API
        let savedContext = NSGraphicsContext.current
        let nsCtx = NSGraphicsContext(cgContext: ctx, flipped: false)
        NSGraphicsContext.current = nsCtx

        // Flip the coordinate system for AppKit text rendering (AppKit uses top-left origin)
        ctx.saveGState()
        ctx.translateBy(x: 0, y: drawRect.midY * 2)
        ctx.scaleBy(x: 1, y: -1)
        let flippedRect = CGRect(x: drawRect.minX,
                                 y: drawRect.minY,
                                 width: drawRect.width,
                                 height: drawRect.height)
        string.draw(with: flippedRect,
                    options: [.usesLineFragmentOrigin, .truncatesLastVisibleLine],
                    context: nil)
        ctx.restoreGState()

        NSGraphicsContext.current = savedContext
    }
}

// MARK: - Error

enum PDFExportError: LocalizedError {
    case renderFailed

    var errorDescription: String? {
        "Could not render PDF data."
    }
}

// MARK: - Helpers

private extension Array {
    /// Splits the array into consecutive chunks of size `size`.
    func chunked(into size: Int) -> [[Element]] {
        stride(from: 0, to: count, by: size).map {
            Array(self[$0..<Swift.min($0 + size, count)])
        }
    }
}

private extension String {
    /// Truncates the string to at most `max` characters, appending "…" if needed.
    func truncated(_ max: Int) -> String {
        guard count > max else { return self }
        return String(prefix(max - 1)) + "…"
    }
}
